name: halal_media
description: "Hala media is a video streaming app. All the content are hala to watch."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.0.0
  fluttertoast: ^8.2.12
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1
  meta: ^1.16.0
  http: ^1.3.0
  dio: ^5.8.0+1
  video_player: ^2.9.5
  youtube_player_flutter: ^9.1.1
  iconsax: ^0.0.8
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  loading_animation_widget: ^1.3.0
  flutter_quill: ^11.2.0
  dropdown_button2: ^2.3.9
  syncfusion_flutter_datepicker: ^29.1.39
  share_plus: ^11.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/banners/
    - assets/icons/
    - assets/icons/navbar/
    - assets/thumbnails/
    - assets/icons/video_player/
